export const SET_USER_AUTHENTICATION = "SET_USER_AUTHENTICATION";
export const SET_USER_AUTH_EXPIRATION = "SET_USER_AUTH_EXPIRATION";
export const POP_USER_AUTHENTICATION = "POP_USER_AUTHENTICATION";
export const DEL_USER_AUTHENTICATION = "DEL_USER_AUTHENTICATION";

export const SET_ALBUMS = "SET_ALBUMS";
export const DEL_ALBUMS = "DEL_ALBUMS";
export const SET_PAGES_ALBUMS = "SET_PAGES_ALBUMS";

export const SET_ARTISTS = "SET_ARTISTS";
export const DEL_ARTISTS = "DEL_ARTISTS";
export const SET_PAGES_ARTISTS = "SET_PAGES_ARTISTS";

export const SET_PLAYLISTS = "SET_PLAYLISTS";
export const DEL_PLAYLISTS = "DEL_PLAYLISTS";
export const SET_PAGES_PLAYLISTS = "SET_PAGES_PLAYLISTS";

export const RESET_COLECTIONS = "RESET_COLECTIONS";

