const { REACT_APP_PROJECT_API_PREFIX, REACT_APP_PROJECT_API_DOMAIN } =
  process.env;

const {
  REACT_APP_SPOTIFY_API_PREFIX,
  REACT_APP_SPOTIFY_API_VERSION,
  REACT_APP_SPOTIFY_API_DOMAIN,
  REACT_APP_SPOTIFY_CLIENT_ID,
  REACT_APP_SPOTIFY_AUTHORIZE_DOMAIN,
} = process.env;

export const CLIENT_APP_URL = `${REACT_APP_PROJECT_API_PREFIX}://${REACT_APP_PROJECT_API_DOMAIN}`;

export const CLIENT_API_REDIRECT_URL = `${CLIENT_APP_URL}/redirect`;

export const SPOTIFY_AUTHORIZE_URL = `${REACT_APP_SPOTIFY_API_PREFIX}://${REACT_APP_SPOTIFY_AUTHORIZE_DOMAIN}?client_id=${REACT_APP_SPOTIFY_CLIENT_ID}&redirect_uri=${CLIENT_API_REDIRECT_URL}&response_type=token&show_dialog=true`;

export const SPOTIFY_API_URL = `${REACT_APP_SPOTIFY_API_PREFIX}://${REACT_APP_SPOTIFY_API_DOMAIN}/${REACT_APP_SPOTIFY_API_VERSION}`;
